### PR TITLE
Add standalone Tool Launch Profile v1p1 extension spec doc.

### PR DESCRIPTION
**Pull request by arwhyte**
Resolves IMSGlobal/caliper-central#141

Raw git view: https://rawgit.com/IMSGlobal/caliper-spec/develop-profile/ToolLaunch-CC141/profiles/toollaunch/caliper-profile-toollaunch-v1p1.html

### CODE REVIEW

**Comment by ViktorHaag** [comment]
What we have seems reasonable; I think we need to seriously consider the case of the LTI message response -- the "Tool Launch" primary use case involves the concept of an "LTI message" (a request that goes via the browser, and in some cases a response that may or may not involve a browser redirection). This happens in two sort of ways:

- the request message contains a `launch_presentation.return_url` claim field (this is the old "when the user is done with your UX workflow, redirect back here, please" URL)

- the request message may, by specification, define a formal response message (see the LTI Deep Linking spec)

In either of these cases, the platform will "known" when an LTI launch results in a come-back from the tool.

This profile seems like it might be incomplete without an event that "catches" this come-back and provides telemetry on it (it may not happen, but if it does happen, it should probably be signalled).

I don't think we necessarily want to release this profile in a half version and then follow up later with this added event -- we should probably add such a thing _now_ if at all... (I can't see a reason we would not want to include it...)

I'm a bit challenged currently on what the verb might be... `HANDLED_RESPONSE` perhaps (seems a bit weak-sauce)?

**Comment by ViktorHaag** [comment]
How about this as a cut for what the `RETURNED` action looks like?
```
{
  "@context": "http://purl.imsglobal.org/ctx/caliper/v1p1/ToolLaunchProfile-extension",
  "id": "urn:uuid:a2e8b214-4d4a-4456-bb4c-099945749117",
  "type": "ToolLaunchEvent",
  "actor": {
    "id": "https://example.edu/users/554433",
    "type": "Person"
  },
  "action": "Returned",
  "object": {   // <-- now this is the platform app
    "id": "https://example.edu",
    "type": "SoftwareApplication"
  },
  "eventTime": "2018-11-15T10:15:00.000Z",
  "edApp": {   // <-- now this is the LTI tool
    "id": "https://example.com/lti/tool",
    "type": "SoftwareApplication"
  },
  "referrer": {   // <-- still the activity from which the launch happened
    "id": "https://example.edu/terms/201801/courses/7/sections/1/pages/1",
    "type": "WebPage"
  },
  "group": {   //  <-- still the context from which the launch happened
    "id": "https://example.edu/terms/201801/courses/7/sections/1",
    "type": "CourseSection",
    "courseNumber": "CPS 435-01",
    "academicSession": "Fall 2018"
  },
  "membership": {   // <-- still the actor's membership in the group
    "id": "https://example.edu/terms/201801/courses/7/sections/1/rosters/1",
    "type": "Membership",
    "member": "https://example.edu/users/554433",
    "organization": "https://example.edu/terms/201801/courses/7/sections/1",
    "roles": [ "Learner" ],
    "status": "Active",
    "dateCreated": "2018-08-01T06:00:00.000Z"
  },
  "session": {   // <-- still the local platform session
    "id": "https://example.edu/sessions/1f6442a482de72ea6ad134943812bff564a76259",
    "type": "Session",
    "startedAtTime": "2018-11-15T10:00:00.000Z"
  },
  "federatedSession": {   // <-- still the federated session
    "id": "https://example.edu/lti/sessions/b533eb02823f31024e6b7f53436c42fb99b31241",
    "type": "LtiSession",
    "user": {
      "id": "https://example.edu/users/554433",
      "type": "Person"
    },
    "messageParameters": {   // <-- this should probably ONLY be used if response WAS a message
    },
    "dateCreated": "2018-11-15T10:15:00.000Z",
    "startedAtTime": "2018-11-15T10:15:00.000Z"
  }
}
```

**Comment by ViktorHaag** [comment]
I would propose that
* Workflows that _have_ a specific "return message" component (i..e deep linking response messages) would populate the `messageParameters` field with the message parameters in the response message.
* We need to think about what to do with _redirections_ as workflow; for some of these, the redirector is allowed to parameterize the URL-for-redirection when the "return pattern" uses that matter... I would suggest that perhaps we add `queryParameters` to the federatedSession meaning "the query parameter values that are operative in your understanding of the session", just like the message parameters are a way of capturing that state in "your understanding of the session".

This second seems to me pretty messy, but maybe it is pragmatic.

**Comment by mgylling** [comment]
@ViktorHaag +1 on the outline. Nice twist there with the inversion of object/edApp... :)

**Comment by ViktorHaag** [comment]
@mgylling in retrospect I think it's potentially too cute, and not a great idea -- it's probably important to be consistently using `edApp` to point to the thing that owns the Sensor emitting the event... in which case it should still be the platform, and the object, the tool (as with ToolLaunchEvent.action==Launched).

@arwhyte thoughts on this?

**Comment by arwhyte** [comment]
@ViktorHaag, @mgylling -- I would reverse the `edApp` and `referrer` values since `edApp` is meant to reference the app context in which the `ToolUseEvent` is minted:

from

```
...
"edApp": {   // <-- now this is the LTI tool
    "id": "https://example.com/lti/tool",
    "type": "SoftwareApplication"
  },
  "referrer": {   // <-- still the activity from which the launch happened
    "id": "https://example.edu/terms/201801/courses/7/sections/1/pages/1",
    "type": "WebPage"
  },
...
```
to
```
...
"edApp": {   // <-- this remains the platform, the app context in which the event is created/emitted
    "id": "https://example.edu",
    "type": "SoftwareApplication"
  },
  "referrer": {   // <-- this refers to the referring tool context
    "id": "https://example.com/lti/tool",
    "type": "SoftwareApplication"
  },
...
```

**Comment by mgylling** [comment]
@arwhyte, @ViktorHaag A stab at adding Returned is now in #315. (Since my original PR was closed I couldn't amend it). Note that there is not yet an attempt to answer the question on how to deal with messageParameters and queryParameters for the Returned action.

**Comment by ViktorHaag** [comment]
How do we want to manage the merger of PRs 315 and 311?

**Comment by arwhyte** [comment]
Closing this PR as it pre-dates subsequent changes that reside in @mgylling's personal branch.  @mgylling will re-open with final changes.

**Pull request closed without merging**
