### PR TITLE
Add constants fixtures

### LINKED ISSUE #473: Add fixture(s) including every LIS Role
Would help implementation libraries stay on point (ex: https://github.com/IMSGlobal/caliper-php/pull/338)

In general it might be good to include fixtures covering all similar constants:
- Actions
- LIS Roles
- LIS Statuses
- LTI Message Types
- System Identifier Types
- Use Metrics

### PR DESCRIPTION
**Pull request by andrew-gardener**
- Actions
- LIS Roles
- LIS Statuses
- LTI Message Types
- System Identifier Types
- Use Metrics

Adds minimal events/entities for each value

Closes #473

### CODE REVIEW

**Comment by bracken** [comment]
It looks good to me, but it'd be nice if @ViktorHaag could give it a quick skim too.

**Comment by andrew-gardener** [comment]
running them through the the dev certification suite and got errors on the LIS Statuses and LIS Roles fixtures. just going to double check if its me or it

**Comment by bracken** [comment]
I wouldn't be surprised if it's the cert suite's fault. I'll run these through the unit tests I have, but it uses the same json-schema so it should be the same result. I'll work on getting it fixed if so.

**Comment by andrew-gardener** [comment]
LIS Statuses was a typo on my part

LIS Roles `Manager#Manager` seems to be missing in the dev cert suite (maybe?)

**Comment by ViktorHaag** [comment]
I like these fixtures but they are not named appropriately, and we should rename them to fit our naming pattern.

All fixtures that use an Envelope as a wrapper need have a name that starts with `caliperEnvelope`.

As these changes seem designed to test vocabulary terms, so I suggest naming them things like:
* `caliperEnvelopeTermAction` (was `caliperActions`)
* `caliperEnvelopeTermLISRole` (was `caliperLISRoles`)
* `caliperEnvelopeTermLISStatus` (was `caliperLISStatuses`) 
* `caliperEnvelopeTermLTIMessageType` (was `caliperLTIMessageTypes`)
* `caliperEnvelopeTermSystemIdentifierType` (was `caliperSystemIdentifierTypes`)
* `caliperEnvelopeTermMetric` (was `caliperUseMetrics`)

The reason we use fixture naming terms like this is so that tests can be written that infer a lot from the file name pattern about what it is they might encounter (vitally, those fixtures with envelopes and those without, for example).

**Comment by andrew-gardener** [comment]
Renamed the fixtures as per @ViktorHaag's comment

**Comment by ViktorHaag** [comment]
@joshuamcghee and @bracken -- we should likely merge this?

**Pull request merged**
