### PR TITLE
Describe suggested use of AggregateMeasureCollection

### PR DESCRIPTION
**Pull request by ViktorHaag**
`ToolUseEvent.generated` has to be an `Entity`, so we should put in wording that makes it clear that by best practice, sensors that want to transmit aggregate metric information should use `ToolUseEvent.generated` to carry an `AggregateMeasureCollection`.

### CODE REVIEW

**Comment by arwhyte** [comment]
I will incorporate these changes in the v1p2 unitary spec.

**Comment by arwhyte** [comment]
@ViktorHaag this PR introduces a merge conflict.  Can you resolve it.

**Comment by ViktorHaag** [comment]
It looks like the upstream file suddenly acquired DOS line-endings, so the merge conflict is essentially the entire file. I'm going to throw away my changes and reimplement them from scratch. We probably need an .editorconfig in this repo to help prevent this from happening again. 8(

**Comment by ViktorHaag** [comment]
Bleh -- resolving the merge conflict basically becomes a change to the entire file because of line-ending mismatches. We can either keep this, or throw away the PR and start from scratch. This repo should have an .editorconfig in it to avoid this problem in the future... 8(

**Comment by ViktorHaag** [comment]
CLosed in favour of https://github.com/IMSGlobal/caliper-spec/pull/446

**Pull request closed without merging**
